---

- name: Put util script
  become: yes
  copy:
    src: find_dt_fmt_name_files.sh
    dest: "{{ xtrabackup_scripts_dir }}"
    owner: "{{ xtrabackup_user }}"
    group: "{{ xtrabackup_user }}"
    mode: "0755"

- name: Put remove scripts
  become: yes
  template:
    src: remove_files.j2
    dest: "{{ xtrabackup_scripts_dir }}/{{ item.name }}"
    owner: "{{ xtrabackup_user }}"
    group: "{{ xtrabackup_user }}"
    mode: "0700"
  loop:
    - name: remove_incremental_backup_dir.sh
      file_type: dir
      days: "{{ xtrabackup_datetimes.incremental.days_duration }}"
      pattern: "^(20[0-9]{2})([01][0-9])([0-9]{2})$"
    - name: remove_full_backup_dir.sh
      file_type: file
      days: "{{ xtrabackup_datetimes.full.days_duration }}"
      pattern: "^(20[0-9]{2})([01][0-9])([0-9]{2}).xbstream$"

## FIXME(@y-hashida):
#  * ansible 2.9.12 以降では以下の cron はすべて「追加」ではなく「上書き」になってしまう.
#  * 回避策を考える.
- name: Register daily cron; Remove incrementals
  cron:
    name: remove_incremental_backup_dir.sh
    user: "{{ xtrabackup_user }}"
    cron_file: "{{ xtrabackup_cron_file }}"
    minute: "31"
    hour: "{{ xtrabackup_datetimes.incremental.removing_hour }}"
    job: "{{ xtrabackup_scripts_dir }}/remove_incremental_backup_dir.sh"
  when:
    - xtrabackup_does_hourly_backup | bool

## FIXME(@y-hashida):
#  * ansible 2.9.12 以降では以下の cron はすべて「追加」ではなく「上書き」になってしまう.
#  * 回避策を考える.
- name: Register daily cron; Remove fulls
  cron:
    name: remove_full_backup_dir.sh
    user: "{{ xtrabackup_user }}"
    cron_file: "{{ xtrabackup_cron_file }}"
    minute: "31"
    hour: "{{ xtrabackup_datetimes.full.removing_hour }}"
    job: "{{ xtrabackup_scripts_dir }}/remove_full_backup_dir.sh"
