---
# handlers/main.yml (xtrabackup)
# Prefix : xtrabackup

- name: "Print warning for xtrabackup (Check for deleted variables)"
  debug:
    msg: "{{ __xtrabackup_check_deleted_vars.stdout_lines }}"
  failed_when: yes
  ignore_errors: yes
